- hosts: master
  become: yes
  tasks:
    - name: add apt_key
      shell:
        cmd: |
          curl https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg | apt-key add - 

    - name: kubernetes.list
      shell:
        cmd: |
          cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
          deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
          EOF

- hosts: node
  become: yes
  tasks:
    - name: add apt_key
      shell:
        cmd: |
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - 

    - name: kubernetes.list
      shell:
        cmd: |
          cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
          deb https://apt.kubernetes.io/ kubernetes-xenial main
          EOF

- hosts: all
  become: yes
  tasks:
    - name: update apt and install curl
      vars: 
        packages:
          - apt-transport-https
          - curl
      apt:
        name: "{{ packages }}"
        state: present

    - name: install docker
      apt:
        name: docker
        state: present
        update_cache: true

    - name: install kubelet kubeadm kubectl
      vars: 
        packages:
          - kubelet
          - kubeadm
          - kubectl
      apt:
        name: "{{ packages }}"
        state: present

    - import_tasks: master.yml
    - import_tasks: node.yml




      